version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
      - image: mysql:5.6
        environment:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes

    working_directory: /app
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
    steps:
      - checkout
